<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RepositoryUrl>https://github.com/georgevella/WolverineFx.Nats.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="3.10.4" />
    <PackageReference Include="NATS.Net" Version="2.5.11"/>
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>
</Project>
